### ISSUE TITLE
frame info

### ISSUE THREAD

**Issue by ytzlax** [RicardoOliveira/ESPProLib#1]
Hi,
thank you on this repository.
can you please tell me the difference between:

receiveraddr

destinationaddr

 transmitteraddr

sourceaddr

thanks

**Comment by RicardoOliveira** [comment]
Hi ytzlax,
The information stored on those fields depends on the packet received. You can see this on esppl_functions.h starting from line 66.
You can also see more information about the WiFi specification (https://en.wikipedia.org/wiki/802.11_Frame_Types).
Take a look at the ESPProLib.ino to see an example of a very simple sniffer.
